선형회귀
==
다루는 내용
--
- 머신러닝 개념
- 경사하강법

In [12]:
import  numpy as np

In [13]:
x = np.random.uniform(low=0.0, high=1.0, size=10)
print(x.shape)
x

(10,)


array([0.37866364, 0.27941652, 0.69265215, 0.98835957, 0.42319402,
       0.10227267, 0.81398303, 0.67569511, 0.48649073, 0.25003503])

종속변수 y = wx + b 생성
--

In [14]:
# w=10 , b=2
y = 100* x + 2000
print (y.shape)
y

(10,)


array([2037.86636408, 2027.94165168, 2069.26521502, 2098.83595664,
       2042.31940181, 2010.227267  , 2081.39830287, 2067.56951064,
       2048.64907255, 2025.00350306])

가중치 w와 절편 b 학습
--

 경사하강법
--

In [15]:
num_epoch = 300

# 초기값은 랜덤하게 지정
w = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

In [16]:
w,b

(0.42048245838699483, 0.05552273566099819)

In [17]:
for epoch in range(num_epoch):
    y_pred = w*x + b
    error = np.abs(y_pred - y).mean()
    if error < 0.05:
        break
    if (epoch % 10) == 0:
        print(f"{epoch:2}  w = {w:.4f} ,  b = {b:.4f} , error = {error:.4f}")
 
    w = w - ((y_pred - y)*x).mean()
    b = b - (y_pred - y).mean()

print("---" * 10)
print(f"{epoch:2}  w = {w:.4f} ,  b = {b:.4f} , error = {error:.4f}")

 0  w = 0.4205 ,  b = 0.0555 , error = 2050.6380
10  w = 532.5732 ,  b = 1767.0892 , error = 100.6805
20  w = 346.9910 ,  b = 1867.0152 , error = 57.4861
30  w = 241.0265 ,  b = 1924.0686 , error = 32.8233
40  w = 180.5231 ,  b = 1956.6448 , error = 18.7414
50  w = 145.9769 ,  b = 1975.2451 , error = 10.7009
60  w = 126.2518 ,  b = 1985.8655 , error = 6.1100
70  w = 114.9892 ,  b = 1991.9295 , error = 3.4887
80  w = 108.5585 ,  b = 1995.3919 , error = 1.9920
90  w = 104.8867 ,  b = 1997.3689 , error = 1.1374
100  w = 102.7902 ,  b = 1998.4977 , error = 0.6494
110  w = 101.5932 ,  b = 1999.1422 , error = 0.3708
120  w = 100.9097 ,  b = 1999.5102 , error = 0.2117
130  w = 100.5194 ,  b = 1999.7203 , error = 0.1209
140  w = 100.2966 ,  b = 1999.8403 , error = 0.0690
------------------------------
146  w = 100.2119 ,  b = 1999.8859 , error = 0.0493


변수가 2개인 경우
--

In [18]:
x1 = np.random.uniform(low=0.0, high=1.0, size=100)
x2 = np.random.uniform(low=0.0, high=1.0, size=100)

y = 10 * x1 + 20* x2 + 2

In [19]:
print(y.shape)
y[:2]

(100,)


array([15.01672231,  7.11738243])

학습속도를 반영
--

In [20]:
num_epoch = 10000
learning_rate = 0.1

w1 = np.random.uniform(low=0.0, high=1.0)
w2 = np.random.uniform(low=0.0, high=1.0)
b = np.random.uniform(low=0.0, high=1.0)

for epoch in range(num_epoch):
    y_pred = w1*x1 + w2*x2 + b
    error = np.abs(y_pred - y).mean()
    if error < 0.01:
        break
    w1 = w1 - learning_rate*((y_pred - y)* x1).mean()
    w2 = w2 - learning_rate*((y_pred - y)* x2).mean()
    b = b -learning_rate* ((y_pred - y)).mean()

    if epoch % 100 == 0:
        print(f"{epoch:2} w1 = {w1:.6f},  w2 = {w2:.6f}, b = {b:.6f} , error = {error:.6f}")

print("---" * 10)
print(f"{epoch:2} w1 = {w1:.4f},  w2 = {w2:.4f}, b = {b:.4f}, error = {error:.4f}")

 0 w1 = 1.214781,  w2 = 1.348375, b = 2.275266 , error = 18.094753
100 w1 = 7.168130,  w2 = 13.157742, b = 7.726010 , error = 1.837044
200 w1 = 7.974804,  w2 = 16.305624, b = 5.361340 , error = 1.044819
300 w1 = 8.625555,  w2 = 17.981962, b = 3.981878 , error = 0.605613
400 w1 = 9.097345,  w2 = 18.885053, b = 3.172845 , error = 0.354700
500 w1 = 9.420151,  w2 = 19.377269, b = 2.696205 , error = 0.209737
600 w1 = 9.633276,  w2 = 19.648630, b = 2.414322 , error = 0.124617
700 w1 = 9.770683,  w2 = 19.799884, b = 2.247087 , error = 0.074227
800 w1 = 9.857813,  w2 = 19.885067, b = 2.147607 , error = 0.044331
900 w1 = 9.912401,  w2 = 19.933498, b = 2.088303 , error = 0.026524
1000 w1 = 9.946297,  w2 = 19.961270, b = 2.052887 , error = 0.015906
------------------------------
1092 w1 = 9.9657,  w2 = 19.9762, b = 2.0332, error = 0.0100


라이브러리를 이용
--

In [21]:
import pandas as pd
from sklearn.linear_model import LinearRegression

X = pd.DataFrame(x1)
X[1]= x2

In [22]:
X

0         1
0   0.171214  0.565229
1   0.007819  0.251960
2   0.282633  0.553403
3   0.046269  0.138076
4   0.838344  0.193940
5   0.426620  0.654379
6   0.797359  0.747410
7   0.855445  0.207972
8   0.533171  0.493959
9   0.604027  0.933505
10  0.674984  0.280155
11  0.469620  0.049964
12  0.362184  0.980279
13  0.446935  0.393512
14  0.567257  0.476570
15  0.592987  0.411936
16  0.389867  0.658656
17  0.675874  0.591524
18  0.263741  0.836459
19  0.463167  0.581549
20  0.022466  0.916717
21  0.849720  0.864821
22  0.800356  0.955934
23  0.360704  0.408270
24  0.386216  0.693362
25  0.308153  0.761207
26  0.761229  0.657404
27  0.605213  0.441385
28  0.297220  0.121769
29  0.452974  0.502006
..       ...       ...
70  0.101842  0.878918
71  0.856105  0.986989
72  0.314957  0.920034
73  0.145410  0.029059
74  0.685851  0.760028
75  0.246162  0.006626
76  0.636686  0.728988
77  0.170338  0.691105
78  0.075842  0.850112
79  0.877616  0.483232
80  0.970168  0.010029
81  0.670189  0.982679
82  0.427163  0.563297
83  0.971991  0.983288
84  0.966406  0.565366
85  0.487651  0.004850
86  0.097144  0.736782
87  0.204472  0.184170
88  0.704700  0.298908
89  0.597684  0.965364
90  0.340233  0.996441
91  0.020831  0.245987
92  0.388975  0.314074
93  0.166137  0.509203
94  0.807147  0.868320
95  0.886209  0.488628
96  0.651647  0.941032
97  0.716432  0.415973
98  0.146876  0.944872
99  0.754366  0.733149

[100 rows x 2 columns]

In [23]:
leg = LinearRegression()
leg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
print(leg.coef_)
print(leg.intercept_)

[10. 20.]
2.0000000000000036
